/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pentaxwifi.gui;

import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import pentaxwifi.CameraConnectionModel;
import pentaxwifi.CameraException;

/**
 *
 * @author Adam
 */
public class LiveViewGui extends javax.swing.JFrame {

    private CameraConnectionModel m;
    
    /**
     * Creates new form LiveViewGui
     */
    public LiveViewGui(CameraConnectionModel m)
    {
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource(MainGui.ICON));
        this.setIconImage(img.getImage());
        
        this.m = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liveViewArea = new javax.swing.JLabel();

        setTitle("Live View");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(749, 532));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        liveViewArea.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(liveViewArea, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(liveViewArea, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Stops live view
     */
    public void end()
    {
        try
        {
            this.m.stopLiveView();
        }
        catch (CameraException ex)
        {
            Logger.getLogger(LiveViewGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        end();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Displays a new image
     * @param img 
     */
    public void updateImage(BufferedImage img)
    {
        if (img == null)
        {
            end();
        }
        else
        {
            this.liveViewArea.setIcon(new ImageIcon(img));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel liveViewArea;
    // End of variables declaration//GEN-END:variables
}
